import { getSupabase } from './supabase';
import { demoDrops } from './mock-data';
import { findSong } from './songs';
import type { MusicDrop } from '@/types/drop';
const STORAGE_KEY='soundmap.drops.v1';
export function getLocalDrops():MusicDrop[]{if(typeof window==='undefined')return demoDrops;try{const saved=window.localStorage.getItem(STORAGE_KEY);return saved?[...JSON.parse(saved) as MusicDrop[],...demoDrops]:demoDrops}catch{return demoDrops}}
export function saveLocalDrop(drop:MusicDrop):void {if(typeof window==='undefined')return;const current=JSON.parse(window.localStorage.getItem(STORAGE_KEY)||'[]') as MusicDrop[];window.localStorage.setItem(STORAGE_KEY,JSON.stringify([drop,...current]));}
export async function fetchDrops(bounds?:{north:number;south:number;east:number;west:number}):Promise<MusicDrop[]>{const supabase=getSupabase();if(supabase){const q=supabase.from('music_drops').select('*, songs(*)').eq('is_active',true);const {data,error}=await q;if(!error&&data)return data.map((row)=>{const raw=row.songs as {id:string;title:string;artist:string;album?:string;cover_url?:string;preview_url?:string;duration?:number};return {...row,song:{id:raw.id,title:raw.title,artist:raw.artist,album:raw.album,coverUrl:raw.cover_url||'',previewUrl:raw.preview_url||'',duration:raw.duration},creatorId:row.creator_id||'',placeName:row.place_name||'Shanghai',clue:row.clue||null,discoveryRadius:row.discovery_radius??800,unlockRadius:row.unlock_radius,discoveryCount:row.discovery_count,isActive:row.is_active,createdAt:row.created_at} as MusicDrop});}const all=getLocalDrops();return bounds?all.filter(d=>d.latitude<=bounds.north&&d.latitude>=bounds.south&&d.longitude>=bounds.west&&d.longitude<=bounds.east):all;}
export async function createDrop(drop:MusicDrop):Promise<void>{const supabase=getSupabase();if(!supabase){saveLocalDrop(drop);return;}const {error}=await supabase.from('music_drops').insert({id:drop.id,creator_id:drop.creatorId,song_id:drop.song.id,latitude:drop.latitude,longitude:drop.longitude,place_name:drop.placeName,note:drop.note,clue:drop.clue||null,visibility:drop.visibility,discovery_radius:drop.visibility==='hidden'?800:drop.discoveryRadius,unlock_radius:drop.unlockRadius,discovery_count:0,is_active:true});if(error)saveLocalDrop(drop);}
export function resolveSong(songId:string){return findSong(songId)}
